GET_LINKS = [
    'configs',
    # 'currencies/rates/exchange',
    # 'news',
    # 'banners',
    # 'points/types',
    # 'points/operationTypes',
    # 'points?_offset=0&_limit=1000',
    # 'cards',
    # 'cards/cardTerms'
    # 'accounts',
    # 'deposits',
    # 'users',
    # 'users/services',
    # 'users/notifications',
    # 'users/photo',
    # 'users/requisites',
    # 'mails/input',
    # 'deposits/offers',
    # 'operations',
    # 'schedules/2017-09-04T19:47:47/2017-10-01T20:59:59',
    # 'cards/bins',
    # 'budgetAccountMasks',
    # 'credits',
    # 'services',
    # 'invoices',
    # 'pushNotifications',
    # 'services/checkLoginSession',
    # 'inquiryTypes',
    # 'cards/_0gXAahgdchUIPVI57xIklVnu_du0c-780IIRfcBjCStSEEE6Iymc0GU0Fwl/statement/2017-09-13T08:47:00/2017-09-20T08:47:00',
    # 'countries',
    # 'bankServices',
    # 'transfers/trustedRecipients',
]

POST_LINKS = [
    ('operations/search', {"filter":{"and":[{"or":[{"column":"toId","op":"=","value":"_0gXAahgdchUIPVI57xIklVnu_du0c-780IIRfcBjCStSEEE6Iymc0GU0Fwl"},{"column":"fromId","op":"=","value":"_0gXAahgdchUIPVI57xIklVnu_du0c-780IIRfcBjCStSEEE6Iymc0GU0Fwl"}]}]},"limit":100,"offset":0}),
    ('serviceOperations/search', {"filter":{"and":[{"column":"targetId","op":"=","value":"_0gXAahgdchUIPVI57xIklVnu_du0c-780IIRfcBjCStSEEE6Iymc0GU0Fwl"}]},"limit":100,"offset":0}),
]
